name: 'Build application'
description: 'Build project and push to docker hub'
inputs:
  image:
    description: "the name of the image"
    required: true
  app-path:
    required: true
    description: "Application path"
  prefix-tag:
    required: false
    description: "Prefixed used in alpha for the tag image"
    default: ""
  docker-file-name:
    required: false
    description: "docker file name"
    default: "Dockerfile"

runs:
  using: "composite"
  steps:
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ env.IMAGE }}
        tags: |
          type=semver,pattern={{version}}
          type=sha
          latest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          PACKAGE_VERSION=${{ steps.python_package_vars.outputs.package_version }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}