name: Build docker Image for docker hub

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

env:
  IMAGE: 'prestashopcorp/ascend-great-expectations-gcs'

jobs:

 build_ascend_ge_image:
    name: Build custom ascend/GE image for docker Hub
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
       python-version: '3.7'

    - name: Build and publish python package
      id: python_package
      uses: ./.github/actions/build_publish_python
      with: 
        pypi-token: ${{ secrets.PYPI_API_TOKEN }}
        package-name: ascend-great-expectations-gcs
    
    - name: Print package version
      run: echo ${{ steps.python_package.outputs.package-version }}

    # - name: Docker meta
    #   id: meta
    #   uses: docker/metadata-action@v3
    #   with:
    #     images: |
    #       ${{ env.IMAGE }}
    #     tags: |
    #       type=semver,pattern={{version}}
    #       type=sha
    #       latest

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1

    # - name: Login to DockerHub
    #   uses: docker/login-action@v1 
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Build and push
    #   id: docker_build
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ steps.meta.outputs.tags }}
    #     labels: ${{ steps.meta.outputs.labels }}
    #     build-args: |
    #       PACKAGE_VERSION=${{ steps.python_package_vars.outputs.package_version }}

    # - name: Image digest
    #   run: echo ${{ steps.docker_build.outputs.digest }}